// SUCCESS API REQUEST TYPES
exports.SUCCESS = 'SUCCESS'
exports.ERROR = 'ERROR'

// REGISTER_SUCCESS
exports.REGISTER_SUCCESSFULLY = 'REGISTER_SUCCESSFULLY'

// LOGIN_SUCCESS
exports.LOGIN_SUCCESSFULLY = 'LOGIN_SUCCESSFULLY'
